version: '3.7'

services:
   server:
      build: ./server
      expose: 
         - 8080
      ports: 
         - 8080:8080
      volumes:
         - ./server:/usr/src/app
   
   client:
      build: ./client
      expose: 
         - 3000
      ports: 
         - 3000:3000
      stdin_open: true
      volumes:
         - ./client:/usr/src/app
   
   mongo:
      image: mongo
      ports:
        - "27017:27017"