version: '3.7'

services:
   server:
      build: ./server
      expose: 
         - 8080
      ports: 
         - 8080:8080
      volumes:
         - ./server:/usr/src/app
   
   client:
      build: ./client
      expose: 
         - 4000
      ports: 
         - 4000:4000
      links: 
         - server
   
   mongo:
      image: mongo
      ports:
        - "27017:27017"